In [1]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse import eye
# from sklearn import metrics
from scipy.sparse.linalg import inv

In [2]:
healthy_df = pd.read_excel('features_30_9_healthy.xlsx', header=None)

In [3]:
healthy_df

0        1        2        3        4        5         6        7   \
0     0.09242  0.58207  0.84332  1.85755  0.75574  9.51179   6.68282  3.31333   
1     0.06342  0.96902  0.74959  1.93489  0.67394  6.65879   6.44094  3.35085   
2     0.10062  0.68576  0.79684  1.68772  0.73787  9.50464   6.04032  3.17706   
3     0.05449  0.74973  0.87516  3.00270  0.71925  7.70397  10.57323  3.66807   
4     0.07776  0.70084  0.85559  2.42659  0.73281  8.71716   8.64065  3.42859   
...       ...      ...      ...      ...      ...      ...       ...      ...   
2103  0.06155  0.69752  0.89054  3.18606  0.74120  7.02580  11.77003  3.62602   
2104  0.06068  0.75961  0.86736  2.86349  0.71831  7.67092  10.40712  3.60249   
2105  0.09644  0.70322  0.85896  2.49303  0.74774  6.01145   9.14703  3.34126   
2106  0.12647  0.66081  0.88106  2.77796  0.75613  5.16639  10.15986  3.13970   
2107  0.12322  0.65647  0.87699  2.66837  0.76188  6.34509   9.91083  3.27109   

           8        9   ...       23          24     25     26    27     28  \
0     3.98427  0.32795  ...  4.82094  4539.14893   9787  12757  5068   7689   
1     4.40313  0.47218  ...  4.26796  2038.07898  10136  12932  8039   4893   
2     3.93885  0.38197  ...  4.53904  4157.31250   9961  12583  5592   6991   
3     4.57908  0.39824  ...  5.20089  3706.43335   8388  12233  4544   7689   
4     4.24003  0.38487  ...  5.10152  4775.73877   9088  12583  3845   8738   
...       ...      ...  ...      ...         ...    ...    ...   ...    ...   
2103  4.42574  0.39767  ...  4.90722  3821.18237   5915  10883  2129   8754   
2104  4.47293  0.40430  ...  4.86279  4307.60449   5678  10646  1656   8990   
2105  4.10024  0.41432  ...  4.70639  3502.35352   4495  10646  1420   9226   
2106  3.91218  0.39423  ...  4.47165  2767.90771   4022  10410  1656   8754   
2107  3.97261  0.40030  ...  4.89185  4565.53125   4259  12066   473  11593   

               29          30  31  \
0     1721357.125  1312.00500   1   
1      702499.750   838.15259   1   
2     1237559.375  1112.45642   1   
3     2748470.500  1657.85120   1   
4     2867137.750  1693.26245   1   
...           ...         ...  ..   
2103  3848079.250  1961.65222   1   
2104  3530869.500  1879.06079   1   
2105  3042845.750  1744.37549   1   
2106  3174905.250  1781.82642   1   
2107  5180411.500  2276.05176   1   

                                                     32  
0     AAL09091956__20181106__12038__CT__HEAD__0002__...  
1     AAL09091956__20181106__12038__CT__HEAD__0002__...  
2     AAL09091956__20181106__12038__CT__HEAD__0002__...  
3     AAL09091956__20181106__12038__CT__HEAD__0002__...  
4     AAL09091956__20181106__12038__CT__HEAD__0002__...  
...                                                 ...  
2103  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
2104  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
2105  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
2106  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
2107  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  

[2108 rows x 33 columns]

In [4]:
nneg = len(healthy_df)  # number of rows of healthy_df
healthy_names = healthy_df.iloc[:,32]  # all file names of healthy_df
unique_healthy_names = healthy_names.unique()  # unique file names of healthy_df
iN = healthy_names.factorize()[0]  # index of unique file names
n_files = len(unique_healthy_names)  # number of unique files

Xneg = healthy_df.iloc[:,:31]  # healthy_df feautures

In [5]:
insult_df = pd.read_excel('features_30_9_insult.xlsx', header=None)

In [6]:
insult_df

0        1        2        3        4        5         6        7   \
0     0.06081  0.75858  0.85508  2.61725  0.71279  9.07447   9.53269  3.54796   
1     0.05805  0.80593  0.86047  2.88797  0.70327  8.43171  10.18995  3.56138   
2     0.05735  0.80487  0.86085  2.89208  0.69992  8.27271  10.48810  3.61427   
3     0.07138  0.60490  0.87878  2.49509  0.74577  7.20000   9.16320  3.48943   
4     0.06371  0.61074  0.88761  2.71714  0.74178  8.10054   9.98028  3.60307   
...       ...      ...      ...      ...      ...      ...       ...      ...   
5930  0.06646  0.65228  0.89100  2.99205  0.75269  8.06304  10.62932  3.63314   
5931  0.06672  0.58668  0.89720  2.85336  0.75804  8.28487  10.18638  3.62216   
5932  0.07679  0.60400  0.87018  2.32624  0.75293  8.35847   8.05221  3.45328   
5933  0.07262  0.62511  0.87357  2.47208  0.74652  8.93944   8.51236  3.49029   
5934  0.06230  0.69481  0.89006  3.15996  0.73572  8.59569  11.16692  3.61403   

           8        9   ...          24    25     26    27    28           29  \
0     4.38729  0.39242  ...  3644.60889  7689  10486  4019  6467  1706812.750   
1     4.49190  0.41046  ...  3413.93018  7340  10486  4019  6467  1868834.875   
2     4.52479  0.40255  ...  3305.78662  6990  10311  3845  6466  1798897.125   
3     4.20273  0.32976  ...  3614.73560  7340  11884  3845  8039  2424746.750   
4     4.32808  0.32754  ...  4149.30322  8214  12058  3845  8213  2890672.500   
...       ...      ...  ...         ...   ...    ...   ...   ...          ...   
5930  4.42857  0.38109  ...  4524.91455  6861  11120  2129  8991  3640547.750   
5931  4.34481  0.33563  ...  4755.65234  6861  11120  1893  9227  3537324.750   
5932  4.18973  0.34140  ...  4798.49463  6861  11120  1893  9227  2920900.750   
5933  4.25676  0.34790  ...  5113.42432  7098  11120  1893  9227  3107574.750   
5934  4.44903  0.38554  ...  4887.35889  7098  11120  1893  9227  4060280.250   

              30       31       32  \
0     1306.45044  0.09679  0.44111   
1     1367.05334  0.14702  0.57444   
2     1341.22974  0.19660  0.60778   
3     1557.15979  0.24542  0.55333   
4     1700.19775  0.29329  0.48111   
...          ...      ...      ...   
5930  1908.02197  0.55711  0.62222   
5931  1880.77771  0.45430  0.67111   
5932  1709.06421  0.34919  0.69000   
5933  1762.83142  0.24275  0.63889   
5934  2015.01367  0.13546  0.47444   

                                                     33  
0     AAL09091956__20181106__12038__CT__HEAD__0002__...  
1     AAL09091956__20181106__12038__CT__HEAD__0002__...  
2     AAL09091956__20181106__12038__CT__HEAD__0002__...  
3     AAL09091956__20181106__12038__CT__HEAD__0002__...  
4     AAL09091956__20181106__12038__CT__HEAD__0002__...  
...                                                 ...  
5930  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
5931  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
5932  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
5933  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
5934  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  

[5935 rows x 34 columns]

In [7]:
insult_32_feature = insult_df.iloc[:,31]  # вероятности больных по расст от центра
insult_33_feature = insult_df.iloc[:,32]  # вероятности больных по пересеч с маской

In [8]:
insult_33_feature.where(insult_33_feature<0.95, other=1, inplace=True)
big_prob_33_feature = insult_33_feature > 0.05  # there is no feature less than 0.05
insult_32_feature = insult_32_feature[big_prob_33_feature]
insult_33_feature = insult_33_feature[big_prob_33_feature]

In [9]:
Y_pos_0 = pd.concat([insult_33_feature, pd.Series(np.zeros((nneg,), dtype=int))], axis=0)  # вероятности больных

In [10]:
Y_pos_0  # вероятности больных

0       0.44111
1       0.57444
2       0.60778
3       0.55333
4       0.48111
         ...   
2103    0.00000
2104    0.00000
2105    0.00000
2106    0.00000
2107    0.00000
Length: 8043, dtype: float64

In [11]:
insult_names = insult_df.iloc[:,33]  # all file names of insult_df
insult_names = insult_names[big_prob_33_feature]

Xpos = insult_df[big_prob_33_feature].iloc[:,:31]  # features of insult_df
npos = len(Xpos)

In [12]:
unique_insult_names = insult_names.unique()  # unique file names in insult_df
iP = insult_names.factorize()[0]  # index of unique file names

In [13]:
indexes = np.concatenate([iP, iN], axis=0)
X0 = pd.concat([Xpos, Xneg], axis=0)

In [14]:
indexes

array([ 0,  0,  0, ..., 45, 45, 45], dtype=int64)

In [15]:
K = 2

In [16]:
mu = X0.mean()
sig = X0.std()
X0 = (X0 - mu)/sig

In [17]:
X0

0         1         2         3         4         5         6   \
0    -0.658769 -0.388568  0.998650  0.893271  0.168592  1.007406  0.996314   
1    -0.768904 -0.176755  1.068378  1.325875 -0.045791  0.465373  1.266773   
2    -0.796837 -0.181497  1.073294  1.332442 -0.121230  0.331290  1.389460   
3    -0.236982 -1.076033  1.305248  0.698062  0.911277 -0.573315  0.844271   
4    -0.543047 -1.049908  1.419478  1.052893  0.821425  0.186101  1.180495   
...        ...       ...       ...       ...       ...       ...       ...   
2103 -0.629240 -0.661711  1.457382  1.802215  0.808364 -0.720216  1.916966   
2104 -0.663956 -0.383961  1.157511  1.286756  0.292898 -0.176193  1.356137   
2105  0.763015 -0.636213  1.048844  0.694770  0.955640 -1.575607  0.837618   
2106  1.961335 -0.825928  1.334743  1.150081  1.144576 -2.288238  1.254391   
2107  1.831647 -0.845342  1.282091  0.974959  1.274062 -1.294252  1.151917   

            7         8         9   ...        21        22        23  \
0     1.102418  0.480440 -0.489884  ... -0.333025 -1.016576  0.676326   
1     1.169118  0.840055 -0.277057  ... -0.589243 -1.096587  0.822323   
2     1.431993  0.953120 -0.370375  ... -0.616231 -1.059719  0.721063   
3     0.811511 -0.154018 -1.229118  ... -0.706493 -1.333484  1.291670   
4     1.376327  0.276895 -1.255308  ... -0.629795 -1.619799  1.687822   
...        ...       ...       ...  ...       ...       ...       ...   
2103  1.490393  0.612618 -0.427947  ... -0.879920 -1.132671  0.862539   
2104  1.373444  0.774842 -0.349730  ... -0.723328 -0.971079  0.746437   
2105  0.075074 -0.506346 -0.231518  ... -0.857973 -0.356089  0.337741   
2106 -0.926722 -1.152835 -0.468531  ... -0.981808  0.668371 -0.275668   
2107 -0.273686 -0.945096 -0.396920  ... -0.858697 -0.480813  0.822375   

            24        25        26        27        28        29        30  
0    -1.419898 -1.606353 -1.792862 -0.994495 -1.588028 -1.001290 -1.372388  
1    -1.452464 -1.638076 -1.792862 -0.994495 -1.588028 -0.995633 -1.349013  
2    -1.467731 -1.669890 -1.803664 -1.017111 -1.588102 -0.998075 -1.358973  
3    -1.424115 -1.638076 -1.706570 -1.017111 -1.471346 -0.976223 -1.275687  
4    -1.348647 -1.558632 -1.695829 -1.017111 -1.458430 -0.959956 -1.220516  
...        ...       ...       ...       ...       ...       ...       ...  
2103 -1.394970 -1.767604 -1.768357 -1.240160 -1.418275 -0.926528 -1.119671  
2104 -1.326298 -1.789147 -1.782986 -1.301641 -1.400757 -0.937603 -1.151527  
2105 -1.439981 -1.896678 -1.782986 -1.332317 -1.383240 -0.954642 -1.203477  
2106 -1.543667 -1.939672 -1.797553 -1.301641 -1.418275 -0.950032 -1.189031  
2107 -1.289885 -1.918129 -1.695335 -1.455409 -1.207549 -0.880009 -0.998404  

[8043 rows x 31 columns]

In [18]:
n = npos + nneg
Y1M0 = pd.concat([insult_33_feature, pd.Series(np.zeros((nneg,), dtype=int))], axis=0)  # вероятности больных по маскам

In [19]:
# quality metrics
qual_1 = np.zeros((5,), dtype=int)
qual_2 = np.zeros((5,), dtype=int)

In [20]:
n_certain_files = 0
n_uncertain_files = n_files - 1
n_test_files = n_files - n_uncertain_files - n_certain_files

In [58]:
from sklearn.cluster import DBSCAN
from scipy.sparse import hstack

def clus_en_matrix(X, L):
    l=L
    n = len(X)
    #for l in range(1,L+1):
    C = DBSCAN(eps=l, min_samples=2).fit(X)
    c_mem = C.labels_
    c_mem[c_mem==-1]=1
    print(c_mem)
    print(len(np.unique(c_mem)))
        
    A_m = csr_matrix((np.ones(n, dtype='int'),
                (np.arange(n),c_mem)), shape=(n,len(np.unique(c_mem))))
    #print(A_m[l].shape)
        
    A = A_m
    A = np.sqrt(1/L)*A
    return A


In [59]:
clus_en_matrix(X, 1.2)  # to which clusters belongs to

[  0   1   0 ... 238 238 238]
455


<8043x455 sparse matrix of type '<class 'numpy.float64'>'
	with 8043 stored elements in Compressed Sparse Row format>

In [22]:
pd.set_option('display.max_columns', 6)

In [70]:
for n_file in range(n_files):
    inp_files = [i for i in range(n_files) if i!=n_file] + [n_file]
    inp = []
    for j in range(n_files):
        ind_files = [i for i, x in enumerate(indexes) if x==inp_files[j]]  # all indexes with number 1,2,3,...,46,1
        inp.extend(ind_files)  # concatenate indexes in loop
    new_indexes = indexes[inp]  # новый порядок объектов
    
    # какие объекы в последних контрольных снимках
    tes_test = np.isin(indexes, inp_files[len(inp_files)-n_test_files:len(inp_files)])  # inp_files[46:46]
    n_test_0 = sum(tes_test)  # количество объектов в контрольной выборке = 277
        
    # какие объекы в неточных снимках
    tes_uncertain = np.isin(indexes, inp_files[n_certain_files:n_certain_files+n_uncertain_files])  # 1,2,...,45
    n_uncertain = sum(tes_uncertain)  # количество объектов в неточной выборке = 7766
        
    # какие объекы в точных снимках
    tes_certain = np.isin(indexes, inp_files[:n_certain_files])  # empty
    n_certain = sum(tes_certain)  # количество объектов в точной выборке = 0
        
    X = X0.iloc[inp]
    Y_pos = Y_pos_0.iloc[inp]
    Y1M = Y1M0.iloc[inp]
    
    ind_insult = Y1M==1  # уверенно классиф как больные
    ind_healthy = Y1M==0  # уверенно классиф как здоровые
    ind_certain = np.logical_or(ind_insult,ind_healthy)  # 4958 уверенно классифицированных данных
    
    Y10Tr = np.array([[*ind_insult[:n_certain], *Y_pos[n_certain:n_certain+n_uncertain], *pd.Series(np.zeros((n_test_0,), dtype=int))],
                      [*ind_healthy[:n_certain], *(1-Y_pos[n_certain:n_certain+n_uncertain]), *pd.Series(np.zeros((n_test_0,), dtype=int))]]).T
    
    Y1MC = Y1M[n-n_test_0:len(Y1M)]  # 8043-277 : 8043 (last)
    Y_true_test = 1+(Y1MC[ind_certain[n-n_test_0:len(ind_certain)]]==0)
    
#     Y10Tr2 = Y10Tr
#     ind_uncertain = np.logical_not(ind_certain)
#     Y10Tr2[ind_uncertain][n_certain:n-n_test_0, :] = 0
    
    #print(Y10Tr2)
    
    sigma = 1.25
    bet = 0.001
    mmax = 1000
    G = bet * eye(n, dtype='int') + csr_matrix(([*pd.to_numeric(ind_certain[:n_certain], errors='coerce'),
                 *np.ones(n_uncertain, dtype='int'),
                 *np.zeros(n_test_0, dtype='int')],
                (np.arange(n),np.arange(n))), shape=(n,n))
    G2 = bet * eye(n, dtype='int') + csr_matrix(([*pd.to_numeric(ind_certain[:n-n_test_0], errors='coerce'),
                  *np.zeros(n_test_0, dtype='int')],
                (np.arange(n),np.arange(n))), shape=(n,n))
    
    A = clus_en_matrix(X,1.2)
    m = A.shape[1]  # 1046 in order of 1055
    u = A.sum(axis = 0)  # by columns
    dd = A * u.conj().transpose()  # 8043x1 array
    dd[dd<0] = 0
    D = csr_matrix(([item for sublist in dd.tolist() for item in sublist], 
                    (np.arange(n), np.arange(n))), shape=(n,n), dtype='int')
    D = csr_matrix((1/np.sqrt(D.diagonal()),
                    (np.arange(n), np.arange(n))), shape=(n,n))
    U = D*A
    Gm = csr_matrix((1/G.diagonal(),
                    (np.arange(n), np.arange(n))), shape=(n,n))
    A1 = bet * Gm * U
    A2 = eye(m, dtype='int') - bet*(U.conj().transpose() * Gm)*U

    F = np.empty(shape=[n,K]) 
    for k in range(K):
        A3 = inv(A2) * (U.conj().transpose() * Gm * Y10Tr[:,k])
        F[:,k] = Gm * Y10Tr[:,k] + A1 * A3
        
    #F = F/F.sum(axis = 1).reshape((n,1))  # нормировка
    Ff = F[n-n_test_0:,]
    Ft = Ff[ind_certain[n-n_test_0:],]

    class11 = Ft[Y_true_test==2, 0]  # negative
    class21 = Ft[Y_true_test==1, 0]  # positive
    roc_curve(class11, class21, 1)
    print(n_file)



[  0   1   0 ... 238 238 238]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6605292156037064
Distance: [0.28009208]
Sensitivity: 0.9558823529411765
Specificity: 0.723404255319149
Accuracy: 0.8961748633879781
PPV: 0.9090909090909091
NPV: 0.85
FNR: 0.04411764705882353
FPR: 0.2765957446808511
FDR: 0.09090909090909091
FOR: 0.15
F1 score: 0.931899641577061
TP: 130
FP: 13
FN: 6
TN: 34
0
[ 0  0  0 ...  1 22  1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6350688841352744
Distance: [0.39069653]
Sensitivity: 0.9227272727272727
Specificity: 0.6170212765957447
Accuracy: 0.8689138576779026
PPV: 0.918552036199095
NPV: 0.6304347826086957
FNR: 0.07727272727272727
FPR: 0.3829787234042553
FDR: 0.08144796380090498
FOR: 0.3695652173913043
F1 score: 0.9206349206349206
TP: 203
FP: 18
FN: 17
TN: 29
1
[ 0  0  0 ... 22  1 22]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5611036052582012
Distance: [0.47132357]
Sensitivity: 0.9044585987261147
Specificity: 0.5384615384615384
Accuracy: 0.8316326530612245
PPV: 0.8875
NPV: 0.5833333333333334
FNR: 0.09554140127388536
FPR: 0.46153846153846156
FDR: 0.1125
FOR: 0.4166666666666667
F1 score: 0.8958990536277602
TP: 142
FP: 18
FN: 15
TN: 21
2
[ 0  0  0 ...  1 22  1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5567766829093986
Distance: [0.50391817]
Sensitivity: 0.9372822299651568
Specificity: 0.5
Accuracy: 0.8958990536277602
PPV: 0.9471830985915493
NPV: 0.45454545454545453
FNR: 0.0627177700348432
FPR: 0.5
FDR: 0.0528169014084507
FOR: 0.5454545454545454
F1 score: 0.9422066549912435
TP: 269
FP: 15
FN: 18
TN: 15
3
[ 0  0  0 ... 22 22  1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.560927957138153
Distance: [0.43745645]
Sensitivity: 0.9122807017543859
Specificity: 0.5714285714285714
Accuracy: 0.864321608040201
PPV: 0.9285714285714286
NPV: 0.5161290322580645
FNR: 0.08771929824561403
FPR: 0.42857142857142855
FDR: 0.07142857142857142
FOR: 0.4838709677419355
F1 score: 0.9203539823008849
TP: 156
FP: 12
FN: 15
TN: 16
4
[  0   0   0 ...  60  22 312]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.565791398619197
Distance: [0.36514198]
Sensitivity: 0.8888888888888888
Specificity: 0.6521739130434783
Accuracy: 0.7889908256880734
PPV: 0.7777777777777778
NPV: 0.8108108108108109
FNR: 0.1111111111111111
FPR: 0.34782608695652173
FDR: 0.2222222222222222
FOR: 0.1891891891891892
F1 score: 0.8296296296296296
TP: 56
FP: 16
FN: 7
TN: 30
5
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6151365954172051
Distance: [0.27906977]
Sensitivity: 1.0
Specificity: 0.7209302325581395
Accuracy: 0.76
PPV: 0.3684210526315789
NPV: 1.0
FNR: 0.0
FPR: 0.27906976744186046
FDR: 0.631578947368421
FOR: 0.0
F1 score: 0.5384615384615384
TP: 7
FP: 12
FN: 0
TN: 31
6
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.564051159312309
Distance: [0.42925629]
Sensitivity: 0.6086956521739131
Specificity: 0.8235294117647058
Accuracy: 0.7
PPV: 0.8235294117647058
NPV: 0.6086956521739131
FNR: 0.391304347826087
FPR: 0.17647058823529413
FDR: 0.17647058823529413
FOR: 0.391304347826087
F1 score: 0.7
TP: 14
FP: 3
FN: 9
TN: 14
7
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: -0.3910163158645353
Distance: [1.]
Sensitivity: 1.0
Specificity: 0.0
Accuracy: 0.42857142857142855
PPV: 0.42857142857142855
NPV: nan
FNR: 0.0
FPR: 1.0
FDR: 0.5714285714285714
FOR: nan
F1 score: 0.6
TP: 30
FP: 40
FN: 0
TN: 0
8


C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:60: RuntimeWarning: invalid value encountered in long_scalars
  print('FOR:', FN/(FN+TN))


[ 0  0  0 ...  1 22 22]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.595047596299824
Distance: [0.125]
Sensitivity: 1.0
Specificity: 0.875
Accuracy: 0.9
PPV: 0.6666666666666666
NPV: 1.0
FNR: 0.0
FPR: 0.125
FDR: 0.3333333333333333
FOR: 0.0
F1 score: 0.8
TP: 12
FP: 6
FN: 0
TN: 42
9
[  0   0   0 ...   1   1 385]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.7303467048469919
Distance: [0.47140452]
Sensitivity: 0.6666666666666666
Specificity: 0.6666666666666666
Accuracy: 0.6666666666666666
PPV: 0.4
NPV: 0.8571428571428571
FNR: 0.3333333333333333
FPR: 0.3333333333333333
FDR: 0.6
FOR: 0.14285714285714285
F1 score: 0.5
TP: 12
FP: 18
FN: 6
TN: 36
10
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1.DE


 ROC CURVE PARAMETERS:

Threshold: -0.3996069580786641
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 64
FN: 0
TN: 0
11
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1.DE


 ROC CURVE PARAMETERS:

Threshold: -0.39920947949856883
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 63
FN: 0
TN: 0
12
[ 0  0  0 ... 22 22  1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5668835736360827
Distance: [0.30154437]
Sensitivity: 0.7866666666666666
Specificity: 0.7868852459016393
Accuracy: 0.7867647058823529
PPV: 0.8194444444444444
NPV: 0.75
FNR: 0.21333333333333335
FPR: 0.21311475409836064
FDR: 0.18055555555555555
FOR: 0.25
F1 score: 0.8027210884353742
TP: 59
FP: 13
FN: 16
TN: 48
13
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6628710180639599
Distance: [0.39686477]
Sensitivity: 0.6666666666666666
Specificity: 0.7846153846153846
Accuracy: 0.7383177570093458
PPV: 0.6666666666666666
NPV: 0.7846153846153846
FNR: 0.3333333333333333
FPR: 0.2153846153846154
FDR: 0.3333333333333333
FOR: 0.2153846153846154
F1 score: 0.6666666666666666
TP: 28
FP: 14
FN: 14
TN: 51
14
[  0   0   0 ...   1 218   1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6624533566197517
Distance: [0.65782707]
Sensitivity: 0.36363636363636365
Specificity: 0.8333333333333334
Accuracy: 0.6973684210526315
PPV: 0.47058823529411764
NPV: 0.7627118644067796
FNR: 0.6363636363636364
FPR: 0.16666666666666666
FDR: 0.5294117647058824
FOR: 0.23728813559322035
F1 score: 0.41025641025641024
TP: 8
FP: 9
FN: 14
TN: 45
15
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.49991308481566715
Distance: [0.78149027]
Sensitivity: 0.22857142857142856
Specificity: 0.875
Accuracy: 0.5733333333333334
PPV: 0.6153846153846154
NPV: 0.5645161290322581
FNR: 0.7714285714285715
FPR: 0.125
FDR: 0.38461538461538464
FOR: 0.43548387096774194
F1 score: 0.3333333333333333
TP: 8
FP: 5
FN: 27
TN: 35
16
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5616958112042861
Distance: [0.33685603]
Sensitivity: 0.7352941176470589
Specificity: 0.7916666666666666
Accuracy: 0.75
PPV: 0.9090909090909091
NPV: 0.5135135135135135
FNR: 0.2647058823529412
FPR: 0.20833333333333334
FDR: 0.09090909090909091
FOR: 0.4864864864864865
F1 score: 0.8130081300813008
TP: 50
FP: 5
FN: 18
TN: 19
17
[ 0  0  0 ...  1  1 22]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5689876856108721
Distance: [0.29510801]
Sensitivity: 0.868421052631579
Specificity: 0.7358490566037735
Accuracy: 0.7912087912087912
PPV: 0.7021276595744681
NPV: 0.8863636363636364
FNR: 0.13157894736842105
FPR: 0.2641509433962264
FDR: 0.2978723404255319
FOR: 0.11363636363636363
F1 score: 0.7764705882352941
TP: 33
FP: 14
FN: 5
TN: 39
18
[  0   0   0 ...   1 105  22]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.7291771660538204
Distance: [0.46612084]
Sensitivity: 0.8461538461538461
Specificity: 0.56
Accuracy: 0.7058823529411765
PPV: 0.6666666666666666
NPV: 0.7777777777777778
FNR: 0.15384615384615385
FPR: 0.44
FDR: 0.3333333333333333
FOR: 0.2222222222222222
F1 score: 0.7457627118644068
TP: 44
FP: 22
FN: 8
TN: 28
19
[  0   0   0 ... 188  85   1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.7299015444796554
Distance: [0.3730628]
Sensitivity: 0.9166666666666666
Specificity: 0.6363636363636364
Accuracy: 0.6964285714285714
PPV: 0.4074074074074074
NPV: 0.9655172413793104
FNR: 0.08333333333333333
FPR: 0.36363636363636365
FDR: 0.5925925925925926
FOR: 0.034482758620689655
F1 score: 0.5641025641025641
TP: 11
FP: 16
FN: 1
TN: 28
20
[  0   0   0 ... 204 253   1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1.DE


 ROC CURVE PARAMETERS:

Threshold: -0.39481734145483294
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 50
FN: 0
TN: 0
21
[ 0  0  0 ...  1 22 22]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.7237669140685515
Distance: [0.60780828]
Sensitivity: 0.5454545454545454
Specificity: 0.5964912280701754
Accuracy: 0.5882352941176471
PPV: 0.20689655172413793
NPV: 0.8717948717948718
FNR: 0.45454545454545453
FPR: 0.40350877192982454
FDR: 0.7931034482758621
FOR: 0.1282051282051282
F1 score: 0.3
TP: 6
FP: 23
FN: 5
TN: 34
22
[  0   0   0 ... 136  22   1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.570627249178093
Distance: [0.57570476]
Sensitivity: 0.6666666666666666
Specificity: 0.5306122448979592
Accuracy: 0.5454545454545454
PPV: 0.14814814814814814
NPV: 0.9285714285714286
FNR: 0.3333333333333333
FPR: 0.46938775510204084
FDR: 0.8518518518518519
FOR: 0.07142857142857142
F1 score: 0.24242424242424243
TP: 4
FP: 23
FN: 2
TN: 26
23
[  0   0   0 ...  22  22 149]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.1962768745680937
Distance: [0.91111111]
Sensitivity: 1.0
Specificity: 0.08888888888888889
Accuracy: 0.10869565217391304
PPV: 0.023809523809523808
NPV: 1.0
FNR: 0.0
FPR: 0.9111111111111111
FDR: 0.9761904761904762
FOR: 0.0
F1 score: 0.046511627906976744
TP: 1
FP: 41
FN: 0
TN: 4
24
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1.DE


 ROC CURVE PARAMETERS:

Threshold: 0.04446372128565812
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 30
FN: 0
TN: 0
25
[  0   0   0 ... 192   1   1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.19561260107114348
Distance: [0.93169499]
Sensitivity: 0.8333333333333334
Specificity: 0.08333333333333333
Accuracy: 0.23333333333333334
PPV: 0.18518518518518517
NPV: 0.6666666666666666
FNR: 0.16666666666666666
FPR: 0.9166666666666666
FDR: 0.8148148148148148
FOR: 0.3333333333333333
F1 score: 0.30303030303030304
TP: 5
FP: 22
FN: 1
TN: 2
26
[0 0 0 ... 1 1 5]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6605858180509532
Distance: [0.41684244]
Sensitivity: 0.9351351351351351
Specificity: 0.5882352941176471
Accuracy: 0.8812785388127854
PPV: 0.9251336898395722
NPV: 0.625
FNR: 0.06486486486486487
FPR: 0.4117647058823529
FDR: 0.0748663101604278
FOR: 0.375
F1 score: 0.9301075268817204
TP: 173
FP: 14
FN: 12
TN: 20
27
[0 0 0 ... 1 5 5]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6428542273062412
Distance: [0.75677863]
Sensitivity: 0.898936170212766
Specificity: 0.25
Accuracy: 0.8788659793814433
PPV: 0.9740634005763689
NPV: 0.07317073170731707
FNR: 0.10106382978723404
FPR: 0.75
FDR: 0.025936599423631124
FOR: 0.926829268292683
F1 score: 0.9349930843706777
TP: 338
FP: 9
FN: 38
TN: 3
28
[  0   0   0 ...   1 452   1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1.DE


 ROC CURVE PARAMETERS:

Threshold: -0.11326357901215581
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 69
FN: 0
TN: 0
29
[  0   0   0 ...   1   1 453]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.19473154513974558
Distance: [0.8833377]
Sensitivity: 0.75
Specificity: 0.1527777777777778
Accuracy: 0.3020833333333333
PPV: 0.22784810126582278
NPV: 0.6470588235294118
FNR: 0.25
FPR: 0.8472222222222222
FDR: 0.7721518987341772
FOR: 0.35294117647058826
F1 score: 0.34951456310679613
TP: 18
FP: 61
FN: 6
TN: 11
30
[ 0  0  0 ... 22 22 22]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6846208610584466
Distance: [0.38928164]
Sensitivity: 0.9302325581395349
Specificity: 0.6170212765957447
Accuracy: 0.7666666666666667
PPV: 0.6896551724137931
NPV: 0.90625
FNR: 0.06976744186046512
FPR: 0.3829787234042553
FDR: 0.3103448275862069
FOR: 0.09375
F1 score: 0.7920792079207921
TP: 40
FP: 18
FN: 3
TN: 29
31
[  0   0   0 ...   1 162   1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.568108165254407
Distance: [0.28869002]
Sensitivity: 0.8048780487804879
Specificity: 0.7872340425531915
Accuracy: 0.7954545454545454
PPV: 0.7674418604651163
NPV: 0.8222222222222222
FNR: 0.1951219512195122
FPR: 0.2127659574468085
FDR: 0.23255813953488372
FOR: 0.17777777777777778
F1 score: 0.7857142857142857
TP: 33
FP: 10
FN: 8
TN: 37
32
[ 0  0  0 ... 22 22 22]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5692802263097924
Distance: [0.49523126]
Sensitivity: 0.926829268292683
Specificity: 0.5102040816326531
Accuracy: 0.7
PPV: 0.6129032258064516
NPV: 0.8928571428571429
FNR: 0.07317073170731707
FPR: 0.4897959183673469
FDR: 0.3870967741935484
FOR: 0.10714285714285714
F1 score: 0.7378640776699029
TP: 38
FP: 24
FN: 3
TN: 25
33
[ 0  0  0 ...  1 22  1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5957191033999655
Distance: [0.49329759]
Sensitivity: 0.6666666666666666
Specificity: 0.6363636363636364
Accuracy: 0.6428571428571429
PPV: 0.3333333333333333
NPV: 0.875
FNR: 0.3333333333333333
FPR: 0.36363636363636365
FDR: 0.6666666666666666
FOR: 0.125
F1 score: 0.4444444444444444
TP: 6
FP: 12
FN: 3
TN: 21
34
[  0   0   0 ...   1 318  22]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5679550132258212
Distance: [0.28305144]
Sensitivity: 0.8837209302325582
Specificity: 0.7419354838709677
Accuracy: 0.8
PPV: 0.7037037037037037
NPV: 0.9019607843137255
FNR: 0.11627906976744186
FPR: 0.25806451612903225
FDR: 0.2962962962962963
FOR: 0.09803921568627451
F1 score: 0.7835051546391752
TP: 38
FP: 16
FN: 5
TN: 46
35
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.568751518770576
Distance: [0.30767262]
Sensitivity: 0.8333333333333334
Specificity: 0.7413793103448276
Accuracy: 0.7830188679245284
PPV: 0.7272727272727273
NPV: 0.8431372549019608
FNR: 0.16666666666666666
FPR: 0.25862068965517243
FDR: 0.2727272727272727
FOR: 0.1568627450980392
F1 score: 0.7766990291262136
TP: 40
FP: 15
FN: 8
TN: 43
36
[  0   0   0 ... 106  22 454]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6505659912904048
Distance: [0.29066401]
Sensitivity: 0.9642857142857143
Specificity: 0.7115384615384616
Accuracy: 0.8
PPV: 0.6428571428571429
NPV: 0.9736842105263158
FNR: 0.03571428571428571
FPR: 0.28846153846153844
FDR: 0.35714285714285715
FOR: 0.02631578947368421
F1 score: 0.7714285714285715
TP: 27
FP: 15
FN: 1
TN: 37
37
[  0   0   0 ...   1 454 454]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5667265430419703
Distance: [0.92856107]
Sensitivity: 0.08333333333333333
Specificity: 0.8518518518518519
Accuracy: 0.36
PPV: 0.5
NPV: 0.34328358208955223
FNR: 0.9166666666666666
FPR: 0.14814814814814814
FDR: 0.5
FOR: 0.6567164179104478
F1 score: 0.14285714285714285
TP: 4
FP: 4
FN: 44
TN: 23
38
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.49362929479187667
Distance: [0.82378149]
Sensitivity: 0.1989795918367347
Specificity: 0.8076923076923077
Accuracy: 0.2702702702702703
PPV: 0.8863636363636364
NPV: 0.11797752808988764
FNR: 0.8010204081632653
FPR: 0.19230769230769232
FDR: 0.11363636363636363
FOR: 0.8820224719101124
F1 score: 0.325
TP: 39
FP: 5
FN: 157
TN: 21
39
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.8564069497714999
Distance: [0.35403126]
Sensitivity: 0.6486486486486487
Specificity: 0.9565217391304348
Accuracy: 0.7972027972027972
PPV: 0.9411764705882353
NPV: 0.717391304347826
FNR: 0.35135135135135137
FPR: 0.043478260869565216
FDR: 0.058823529411764705
FOR: 0.2826086956521739
F1 score: 0.768
TP: 48
FP: 3
FN: 26
TN: 66
40
[0 0 0 ... 5 5 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.892074143970603
Distance: [0.7078547]
Sensitivity: 0.3076923076923077
Specificity: 0.8524590163934426
Accuracy: 0.64
PPV: 0.5714285714285714
NPV: 0.6582278481012658
FNR: 0.6923076923076923
FPR: 0.14754098360655737
FDR: 0.42857142857142855
FOR: 0.34177215189873417
F1 score: 0.4
TP: 12
FP: 9
FN: 27
TN: 52
41
[  0   0   0 ...  22 453 445]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.18637203552623302
Distance: [0.88924186]
Sensitivity: 0.9382716049382716
Specificity: 0.11290322580645161
Accuracy: 0.5804195804195804
PPV: 0.5801526717557252
NPV: 0.5833333333333334
FNR: 0.06172839506172839
FPR: 0.8870967741935484
FDR: 0.4198473282442748
FOR: 0.4166666666666667
F1 score: 0.7169811320754716
TP: 76
FP: 55
FN: 5
TN: 7
42
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.18902263890989934
Distance: [0.88482816]
Sensitivity: 0.6219512195121951
Specificity: 0.2
Accuracy: 0.5392156862745098
PPV: 0.7611940298507462
NPV: 0.11428571428571428
FNR: 0.3780487804878049
FPR: 0.8
FDR: 0.23880597014925373
FOR: 0.8857142857142857
F1 score: 0.6845637583892618
TP: 51
FP: 16
FN: 31
TN: 4
43
[  0   0   0 ...   1 150  22]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1.DE


 ROC CURVE PARAMETERS:

Threshold: -0.37822200000000006
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 55
FN: 0
TN: 0
44
[0 0 0 ... 1 1 1]
455


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: -0.3953797614687446
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 41
FN: 0
TN: 0
45


C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_9748/3470959793.py:60: RuntimeWarning: invalid value encountered in long_scalars
  print('FOR:', FN/(FN+TN))


In [67]:
n_file = 0
inp_files = [i for i in range(n_files) if i!=n_file] + [n_file]
inp = []
for j in range(n_files):
    ind_files = [i for i, x in enumerate(indexes) if x==inp_files[j]]  # all indexes with number 1,2,3,...,46,1
    inp.extend(ind_files)  # concatenate indexes in loop
new_indexes = indexes[inp]  # новый порядок объектов

# какие объекы в последних контрольных снимках
tes_test = np.isin(indexes, inp_files[len(inp_files)-n_test_files:len(inp_files)])  # inp_files[46:46]
n_test_0 = sum(tes_test)  # количество объектов в контрольной выборке = 277

# какие объекы в неточных снимках
tes_uncertain = np.isin(indexes, inp_files[n_certain_files:n_certain_files+n_uncertain_files])  # 1,2,...,45
n_uncertain = sum(tes_uncertain)  # количество объектов в неточной выборке = 7766

# какие объекы в точных снимках
tes_certain = np.isin(indexes, inp_files[:n_certain_files])  # empty
n_certain = sum(tes_certain)  # количество объектов в точной выборке = 0

X = X0.iloc[inp]
Y_pos = Y_pos_0.iloc[inp]
Y1M = Y1M0.iloc[inp]

ind_insult = Y1M==1  # уверенно классиф как больные
ind_healthy = Y1M==0  # уверенно классиф как здоровые
ind_certain = np.logical_or(ind_insult,ind_healthy)  # 4958 уверенно классифицированных данных

Y10Tr = np.array([[*ind_insult[:n_certain], *Y_pos[n_certain:n_certain+n_uncertain], *pd.Series(np.zeros((n_test_0,), dtype=int))],
                  [*ind_healthy[:n_certain], *(1-Y_pos[n_certain:n_certain+n_uncertain]), *pd.Series(np.zeros((n_test_0,), dtype=int))]]).T

Y1MC = Y1M[n-n_test_0:len(Y1M)]  # 8043-277 : 8043 (last)
Y_true_test = 1+(Y1MC[ind_certain[n-n_test_0:len(ind_certain)]]==0)

#     Y10Tr2 = Y10Tr
#     ind_uncertain = np.logical_not(ind_certain)
#     Y10Tr2[ind_uncertain][n_certain:n-n_test_0, :] = 0

#print(Y10Tr2)

sigma = 1.25
bet = 0.001
mmax = 1000
G = bet * eye(n, dtype='int') + csr_matrix(([*pd.to_numeric(ind_certain[:n_certain], errors='coerce'),
             *np.ones(n_uncertain, dtype='int'),
             *np.zeros(n_test_0, dtype='int')],
            (np.arange(n),np.arange(n))), shape=(n,n))
G2 = bet * eye(n, dtype='int') + csr_matrix(([*pd.to_numeric(ind_certain[:n-n_test_0], errors='coerce'),
              *np.zeros(n_test_0, dtype='int')],
            (np.arange(n),np.arange(n))), shape=(n,n))

A = clus_en_matrix(X,1.2)
m = A.shape[1]  # 1046 in order of 1055
u = A.sum(axis = 0)  # by columns
dd = A * u.conj().transpose()  # 8043x1 array
dd[dd<0] = 0
D = csr_matrix(([item for sublist in dd.tolist() for item in sublist], 
                (np.arange(n), np.arange(n))), shape=(n,n), dtype='int')
D = csr_matrix((1/np.sqrt(D.diagonal()),
                (np.arange(n), np.arange(n))), shape=(n,n))
U = D*A
Gm = csr_matrix((1/G.diagonal(),
                (np.arange(n), np.arange(n))), shape=(n,n))
A1 = bet * Gm * U
A2 = eye(m, dtype='int') - bet*(U.conj().transpose() * Gm)*U

F = np.empty(shape=[n,K]) 
for k in range(K):
    A3 = inv(A2) * (U.conj().transpose() * Gm * Y10Tr[:,k])
    print('A3 -> ', A3)
    F[:,k] = Gm * Y10Tr[:,k] + A1 * A3
    print('F[:,k] -> ', F[:,k])

#F = F/F.sum(axis = 1).reshape((n,1))  # нормировка
Ff = F[n-n_test_0:,]
Ft = Ff[ind_certain[n-n_test_0:],]

class11 = Ft[Y_true_test==2, 0]  # negative
class21 = Ft[Y_true_test==1, 0]  # positive

[  0   1   0 ... 238 238 238]
455
A3 ->  

C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '


[41.36666196 19.86997331  1.69951558  1.25040865  1.22815429  1.74327833
  1.75692333  1.44197526  2.21641772  2.19773527  1.9302958   1.93697592
  1.66557533  1.82695983  1.82695983  0.          0.5612786   1.06031999
  0.          0.          1.13674695  0.          0.          0.64565864
  0.54098108  1.60519522  0.96727475  0.40598701  1.5151413   1.82695983
  2.04926767  1.22203516  1.35702009  1.82695983  0.          0.
  0.40824829  0.33215263  0.34730411  0.          0.          2.23028584
  1.00876441  1.4111257   1.34890839  1.3448434   1.72444912  1.82695983
  1.82695983  1.93697592  2.44948974  0.          0.          1.11627276
  1.5015179   0.73970731  1.93697592  1.6584776   3.09389294  1.82695983
  1.21168174  0.          0.25881626  0.          0.30449026  0.28767966
  0.79676459  0.43833119  1.10733862  0.37089215  1.36108507  1.41386594
  1.71816866  0.79990003  0.61711049  1.51028375  0.81401109  1.38544758
  1.32555984  1.16824033  1.01092082  0.          0.       

In [66]:
F

array([[0.41144129, 0.58855871],
       [0.39443614, 0.60556386],
       [0.44918354, 0.55081646],
       ...,
       [0.92862961, 0.07137039],
       [0.92862961, 0.07137039],
       [0.92862961, 0.07137039]])

In [62]:
A2.toarray()

array([[ 0.999001  ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.97582194,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.99875125, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.66666667,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.66666667,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.66666667]])

In [63]:
A.toarray()

array([[0.91287093, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.91287093, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.91287093, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [29]:
dd

matrix([[150.7],
        [142.5],
        [159.6],
        ...,
        [141.1],
        [122.2],
        [128.3]])

In [31]:
U.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.02581989],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.02653724],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [32]:
Y10Tr

array([[0.41111, 0.58889],
       [0.39444, 0.60556],
       [0.44889, 0.55111],
       ...,
       [0.     , 0.     ],
       [0.     , 0.     ],
       [0.     , 0.     ]])

In [63]:
len(Y10Tr2[ind_uncertain][n_certain:n-n_test_0, :])  #should be 3001

3085

In [65]:
len(Y10Tr2)

8043

In [64]:
Y10Tr2[ind_uncertain[n_certain:n-n_test_0],:]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 8043 but corresponding boolean dimension is 7766

In [66]:
ind_uncertain[n_certain:n-n_test_0]

230      True
231      True
232      True
233      True
234      True
        ...  
2103    False
2104    False
2105    False
2106    False
2107    False
Length: 7766, dtype: bool

In [68]:
Y10Tr

array([[0.41111, 0.58889],
       [0.39444, 0.60556],
       [0.44889, 0.55111],
       ...,
       [0.     , 0.     ],
       [0.     , 0.     ],
       [0.     , 0.     ]])

In [69]:
def roc_curve(class_1, class_2, disp_data):  # negative, positive
#     rng(1337,'twister')
#     s = rng
#     class_1 = rand(1,3);
#     rng(s)
#     class_2 = 0.5*rand(1,5);
#     sispt = 1;
#     dispp = 1;

#     np.random.seed(1337)
#     class_1 = np.random.rand(1,3)
#     np.random.seed(1337)
#     class_2 = 0.5*np.random.rand(1,3)

    # Calculating the threshold values between the data points
    s_data = np.sort(np.unique(np.concatenate([class_1, class_2], axis=0)))
    s_data = s_data[s_data!=np.array(None)]
    d_data = np.diff(s_data)
    if np.all(d_data==0):
        print('Both class are the same!')
    d_data = np.append(d_data, d_data[-1])
    thres = np.empty(len(s_data)+1)
    thres[0] = s_data[0] - d_data[0]
    thres[1:len(thres)] = s_data + d_data/2

    # Calculating the sensibility and specificity of each threshold
    curve = np.zeros((len(thres),2))
    distance = np.zeros((len(thres),1))
    for id_t in range(len(thres)):
        TP = np.sum(class_2 >= thres[id_t])
        FP = np.sum(class_1 >= thres[id_t])
        FN = np.sum(class_2 < thres[id_t])
        TN = np.sum(class_1 < thres[id_t])

        curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
        curve[id_t, 1] = TN/(TN+FP)  # specificity - FPR

        distance[id_t] = np.sqrt((1-curve[id_t, 0])**2 + (curve[id_t,1]-1)**2)

    # Optimum threshold and parameters
    #opt = np.min(distance)  # 1
    opt = np.argmin(distance)
    TP = np.sum(class_2 >= thres[opt])
    FP = np.sum(class_1 >= thres[opt])
    FN = np.sum(class_2 < thres[opt])
    TN = np.sum(class_1 < thres[opt])

    if disp_data==1:
        print('\n ROC CURVE PARAMETERS:\n')
        print('Threshold:', thres[opt])
        print('Distance:', distance[opt])
        print('Sensitivity:', curve[opt,0])
        print('Specificity:', curve[opt,1])
        print('Accuracy:', (TP+TN)/(TP+TN+FP+FN))
        print('PPV:', TP/(TP+FP))
        print('NPV:', TN/(TN+FN))
        print('FNR:', FN/(FN+TP))
        print('FPR:', FP/(FP+TN))
        print('FDR:', FP/(FP+TP))
        print('FOR:', FN/(FN+TN))
        print('F1 score:', 2*TP/(2*TP+FP+FN))
        print('TP:', TP)
        print('FP:', FP)
        print('FN:', FN)
        print('TN:', TN)