In [1]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse import eye
# from sklearn import metrics
from scipy.sparse.linalg import inv

In [2]:
healthy_df = pd.read_excel('features_30_9_healthy.xlsx', header=None)

In [3]:
healthy_df

0        1        2        3        4        5         6        7   \
0     0.09242  0.58207  0.84332  1.85755  0.75574  9.51179   6.68282  3.31333   
1     0.06342  0.96902  0.74959  1.93489  0.67394  6.65879   6.44094  3.35085   
2     0.10062  0.68576  0.79684  1.68772  0.73787  9.50464   6.04032  3.17706   
3     0.05449  0.74973  0.87516  3.00270  0.71925  7.70397  10.57323  3.66807   
4     0.07776  0.70084  0.85559  2.42659  0.73281  8.71716   8.64065  3.42859   
...       ...      ...      ...      ...      ...      ...       ...      ...   
2103  0.06155  0.69752  0.89054  3.18606  0.74120  7.02580  11.77003  3.62602   
2104  0.06068  0.75961  0.86736  2.86349  0.71831  7.67092  10.40712  3.60249   
2105  0.09644  0.70322  0.85896  2.49303  0.74774  6.01145   9.14703  3.34126   
2106  0.12647  0.66081  0.88106  2.77796  0.75613  5.16639  10.15986  3.13970   
2107  0.12322  0.65647  0.87699  2.66837  0.76188  6.34509   9.91083  3.27109   

           8        9   ...       23          24     25     26    27     28  \
0     3.98427  0.32795  ...  4.82094  4539.14893   9787  12757  5068   7689   
1     4.40313  0.47218  ...  4.26796  2038.07898  10136  12932  8039   4893   
2     3.93885  0.38197  ...  4.53904  4157.31250   9961  12583  5592   6991   
3     4.57908  0.39824  ...  5.20089  3706.43335   8388  12233  4544   7689   
4     4.24003  0.38487  ...  5.10152  4775.73877   9088  12583  3845   8738   
...       ...      ...  ...      ...         ...    ...    ...   ...    ...   
2103  4.42574  0.39767  ...  4.90722  3821.18237   5915  10883  2129   8754   
2104  4.47293  0.40430  ...  4.86279  4307.60449   5678  10646  1656   8990   
2105  4.10024  0.41432  ...  4.70639  3502.35352   4495  10646  1420   9226   
2106  3.91218  0.39423  ...  4.47165  2767.90771   4022  10410  1656   8754   
2107  3.97261  0.40030  ...  4.89185  4565.53125   4259  12066   473  11593   

               29          30  31  \
0     1721357.125  1312.00500   1   
1      702499.750   838.15259   1   
2     1237559.375  1112.45642   1   
3     2748470.500  1657.85120   1   
4     2867137.750  1693.26245   1   
...           ...         ...  ..   
2103  3848079.250  1961.65222   1   
2104  3530869.500  1879.06079   1   
2105  3042845.750  1744.37549   1   
2106  3174905.250  1781.82642   1   
2107  5180411.500  2276.05176   1   

                                                     32  
0     AAL09091956__20181106__12038__CT__HEAD__0002__...  
1     AAL09091956__20181106__12038__CT__HEAD__0002__...  
2     AAL09091956__20181106__12038__CT__HEAD__0002__...  
3     AAL09091956__20181106__12038__CT__HEAD__0002__...  
4     AAL09091956__20181106__12038__CT__HEAD__0002__...  
...                                                 ...  
2103  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
2104  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
2105  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
2106  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
2107  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  

[2108 rows x 33 columns]

In [4]:
nneg = len(healthy_df)  # number of rows of healthy_df
healthy_names = healthy_df.iloc[:,32]  # all file names of healthy_df
unique_healthy_names = healthy_names.unique()  # unique file names of healthy_df
iN = healthy_names.factorize()[0]  # index of unique file names
n_files = len(unique_healthy_names)  # number of unique files

Xneg = healthy_df.iloc[:,:31]  # healthy_df feautures

In [5]:
insult_df = pd.read_excel('features_30_9_insult.xlsx', header=None)

In [6]:
insult_df

0        1        2        3        4        5         6        7   \
0     0.06081  0.75858  0.85508  2.61725  0.71279  9.07447   9.53269  3.54796   
1     0.05805  0.80593  0.86047  2.88797  0.70327  8.43171  10.18995  3.56138   
2     0.05735  0.80487  0.86085  2.89208  0.69992  8.27271  10.48810  3.61427   
3     0.07138  0.60490  0.87878  2.49509  0.74577  7.20000   9.16320  3.48943   
4     0.06371  0.61074  0.88761  2.71714  0.74178  8.10054   9.98028  3.60307   
...       ...      ...      ...      ...      ...      ...       ...      ...   
5930  0.06646  0.65228  0.89100  2.99205  0.75269  8.06304  10.62932  3.63314   
5931  0.06672  0.58668  0.89720  2.85336  0.75804  8.28487  10.18638  3.62216   
5932  0.07679  0.60400  0.87018  2.32624  0.75293  8.35847   8.05221  3.45328   
5933  0.07262  0.62511  0.87357  2.47208  0.74652  8.93944   8.51236  3.49029   
5934  0.06230  0.69481  0.89006  3.15996  0.73572  8.59569  11.16692  3.61403   

           8        9   ...          24    25     26    27    28           29  \
0     4.38729  0.39242  ...  3644.60889  7689  10486  4019  6467  1706812.750   
1     4.49190  0.41046  ...  3413.93018  7340  10486  4019  6467  1868834.875   
2     4.52479  0.40255  ...  3305.78662  6990  10311  3845  6466  1798897.125   
3     4.20273  0.32976  ...  3614.73560  7340  11884  3845  8039  2424746.750   
4     4.32808  0.32754  ...  4149.30322  8214  12058  3845  8213  2890672.500   
...       ...      ...  ...         ...   ...    ...   ...   ...          ...   
5930  4.42857  0.38109  ...  4524.91455  6861  11120  2129  8991  3640547.750   
5931  4.34481  0.33563  ...  4755.65234  6861  11120  1893  9227  3537324.750   
5932  4.18973  0.34140  ...  4798.49463  6861  11120  1893  9227  2920900.750   
5933  4.25676  0.34790  ...  5113.42432  7098  11120  1893  9227  3107574.750   
5934  4.44903  0.38554  ...  4887.35889  7098  11120  1893  9227  4060280.250   

              30       31       32  \
0     1306.45044  0.09679  0.44111   
1     1367.05334  0.14702  0.57444   
2     1341.22974  0.19660  0.60778   
3     1557.15979  0.24542  0.55333   
4     1700.19775  0.29329  0.48111   
...          ...      ...      ...   
5930  1908.02197  0.55711  0.62222   
5931  1880.77771  0.45430  0.67111   
5932  1709.06421  0.34919  0.69000   
5933  1762.83142  0.24275  0.63889   
5934  2015.01367  0.13546  0.47444   

                                                     33  
0     AAL09091956__20181106__12038__CT__HEAD__0002__...  
1     AAL09091956__20181106__12038__CT__HEAD__0002__...  
2     AAL09091956__20181106__12038__CT__HEAD__0002__...  
3     AAL09091956__20181106__12038__CT__HEAD__0002__...  
4     AAL09091956__20181106__12038__CT__HEAD__0002__...  
...                                                 ...  
5930  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
5931  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
5932  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
5933  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  
5934  ZSA29101953__20170511__6862__CT__HEAD__0002__b...  

[5935 rows x 34 columns]

In [7]:
insult_32_feature = insult_df.iloc[:,31]  # вероятности больных по расст от центра
insult_33_feature = insult_df.iloc[:,32]  # вероятности больных по пересеч с маской

In [8]:
insult_33_feature.where(insult_33_feature<0.95, other=1, inplace=True)
big_prob_33_feature = insult_33_feature > 0.05  # there is no feature less than 0.05
insult_32_feature = insult_32_feature[big_prob_33_feature]
insult_33_feature = insult_33_feature[big_prob_33_feature]

In [9]:
Y_pos_0 = pd.concat([insult_33_feature, pd.Series(np.zeros((nneg,), dtype=int))], axis=0)  # вероятности больных

In [10]:
Y_pos_0  # вероятности больных

0       0.44111
1       0.57444
2       0.60778
3       0.55333
4       0.48111
         ...   
2103    0.00000
2104    0.00000
2105    0.00000
2106    0.00000
2107    0.00000
Length: 8043, dtype: float64

In [11]:
insult_names = insult_df.iloc[:,33]  # all file names of insult_df
insult_names = insult_names[big_prob_33_feature]

Xpos = insult_df[big_prob_33_feature].iloc[:,:31]  # features of insult_df
npos = len(Xpos)

In [12]:
unique_insult_names = insult_names.unique()  # unique file names in insult_df
iP = insult_names.factorize()[0]  # index of unique file names

In [13]:
indexes = np.concatenate([iP, iN], axis=0)
X0 = pd.concat([Xpos, Xneg], axis=0)

In [14]:
indexes

array([ 0,  0,  0, ..., 45, 45, 45], dtype=int64)

In [15]:
K = 2

In [16]:
mu = X0.mean()
sig = X0.std()
X0 = (X0 - mu)/sig

In [17]:
X0

0         1         2         3         4         5         6   \
0    -0.658769 -0.388568  0.998650  0.893271  0.168592  1.007406  0.996314   
1    -0.768904 -0.176755  1.068378  1.325875 -0.045791  0.465373  1.266773   
2    -0.796837 -0.181497  1.073294  1.332442 -0.121230  0.331290  1.389460   
3    -0.236982 -1.076033  1.305248  0.698062  0.911277 -0.573315  0.844271   
4    -0.543047 -1.049908  1.419478  1.052893  0.821425  0.186101  1.180495   
...        ...       ...       ...       ...       ...       ...       ...   
2103 -0.629240 -0.661711  1.457382  1.802215  0.808364 -0.720216  1.916966   
2104 -0.663956 -0.383961  1.157511  1.286756  0.292898 -0.176193  1.356137   
2105  0.763015 -0.636213  1.048844  0.694770  0.955640 -1.575607  0.837618   
2106  1.961335 -0.825928  1.334743  1.150081  1.144576 -2.288238  1.254391   
2107  1.831647 -0.845342  1.282091  0.974959  1.274062 -1.294252  1.151917   

            7         8         9   ...        21        22        23  \
0     1.102418  0.480440 -0.489884  ... -0.333025 -1.016576  0.676326   
1     1.169118  0.840055 -0.277057  ... -0.589243 -1.096587  0.822323   
2     1.431993  0.953120 -0.370375  ... -0.616231 -1.059719  0.721063   
3     0.811511 -0.154018 -1.229118  ... -0.706493 -1.333484  1.291670   
4     1.376327  0.276895 -1.255308  ... -0.629795 -1.619799  1.687822   
...        ...       ...       ...  ...       ...       ...       ...   
2103  1.490393  0.612618 -0.427947  ... -0.879920 -1.132671  0.862539   
2104  1.373444  0.774842 -0.349730  ... -0.723328 -0.971079  0.746437   
2105  0.075074 -0.506346 -0.231518  ... -0.857973 -0.356089  0.337741   
2106 -0.926722 -1.152835 -0.468531  ... -0.981808  0.668371 -0.275668   
2107 -0.273686 -0.945096 -0.396920  ... -0.858697 -0.480813  0.822375   

            24        25        26        27        28        29        30  
0    -1.419898 -1.606353 -1.792862 -0.994495 -1.588028 -1.001290 -1.372388  
1    -1.452464 -1.638076 -1.792862 -0.994495 -1.588028 -0.995633 -1.349013  
2    -1.467731 -1.669890 -1.803664 -1.017111 -1.588102 -0.998075 -1.358973  
3    -1.424115 -1.638076 -1.706570 -1.017111 -1.471346 -0.976223 -1.275687  
4    -1.348647 -1.558632 -1.695829 -1.017111 -1.458430 -0.959956 -1.220516  
...        ...       ...       ...       ...       ...       ...       ...  
2103 -1.394970 -1.767604 -1.768357 -1.240160 -1.418275 -0.926528 -1.119671  
2104 -1.326298 -1.789147 -1.782986 -1.301641 -1.400757 -0.937603 -1.151527  
2105 -1.439981 -1.896678 -1.782986 -1.332317 -1.383240 -0.954642 -1.203477  
2106 -1.543667 -1.939672 -1.797553 -1.301641 -1.418275 -0.950032 -1.189031  
2107 -1.289885 -1.918129 -1.695335 -1.455409 -1.207549 -0.880009 -0.998404  

[8043 rows x 31 columns]

In [18]:
n = npos + nneg
Y1M0 = pd.concat([insult_33_feature, pd.Series(np.zeros((nneg,), dtype=int))], axis=0)  # вероятности больных по маскам

In [19]:
# quality metrics
qual_1 = np.zeros((5,), dtype=int)
qual_2 = np.zeros((5,), dtype=int)

In [20]:
n_certain_files = 0
n_uncertain_files = n_files - 1
n_test_files = n_files - n_uncertain_files - n_certain_files

In [75]:
from sklearn.metrics import silhouette_score
from sklearn.cluster import DBSCAN

eps_test = [0.8,0.9,1.0,1.1,1.15,1.16,1.17,1.18,1.2,1.3,1.4]
for i in eps_test:
    C = DBSCAN(eps=i, min_samples=3).fit(X)
    c_mem = C.labels_
    print(c_mem)
    vals, unq_count = np.unique(c_mem, return_counts=True)
    print(unq_count)
    if len(np.unique(c_mem)) > 1:
        print(i, ' -> ', silhouette_score(X, c_mem))
    

[-1 -1 -1 ... -1 -1 -1]
[6584    3    4   39  161   21    3    4    7    3    3   23    3   18
   14   11    5    3    3    3   22    3    3    6    3    4    6    3
   12    3   10    6    5    4    8    7    5    3    3   13   14    4
    8    4    5    3    5   21    4    6   15    3    3    5   16    7
    6    4   12    7    9    7    3    4    7    4    5    3    3    4
    4    3    3    6    3   10    4    6    3    3    3    3    3    5
    6   18    8    5    3    5    4    5    3    3    3    4    3    4
    3    3    5    4    3    4    3    6   11    9    3    4    5    3
    4    3    3    3    3    6    3    3    3    7   12    5    6    6
    4    3    3    4    3    6    4    5    3    3    3    4    8    3
    3    4    3    3    3    3    3    3    4    4    3    4    3    3
    5    3    3    3    3    3    3    3   25    3    3    6    3    4
   16    3    3    3    3   15    6    7    7    3    4    3    4   15
    3    4    7    3    6    5    5    3    3    4   

1.18  ->  -0.4668648191556202
[ 0  0  0 ... -1 -1 -1]
[3142   32    7  822   11    7    3    5    4    3 3102    3    3    4
    4    3    3    9    6    5    3    6    3    5    3    6    6   10
    5    3    3    6    3   14    3    3    3    3    6    8    3    3
    4    6    3    3    7   18    3    3    3    5    3    3    3    3
   12    3    3    3    3    3    7    3    9    3    3    6    4    3
    5    4    4  176    4    3    4    3    3    3    7    3    4    3
    4    3    4    3    3    3    3    3    6    3    3    3    3    3
    4    4    3    4    3    4    3    4    3    8    5    5    3    3
    5    4    4    3    3    3    3    4    4    4    3    3    5    3
    4    3    4    4    4    5   10   10    5    9    3    3    4    5
    3    3    3    3    3    3    4    4    5    4    3    3    4    5
    3    4   25    6    5    3    4    5    5    3    4    5    7    5
    3    3    5    3    8    3    3    4    6]
1.2  ->  -0.4693471407298603
[ 0  0  0 ... -1 -

In [67]:
C = DBSCAN(eps=5, min_samples=3).fit(X)

In [68]:
np.unique(C.labels_, return_counts=True)

(array([-1,  0], dtype=int64), array([  18, 8025], dtype=int64))

In [35]:
from sklearn.cluster import DBSCAN
from scipy.sparse import hstack

def clus_en_matrix(X, L):
    l=L
    n = len(X)
    #for l in range(1,L+1):
    C = DBSCAN(eps=l, min_samples=3).fit(X)
    c_mem = C.labels_
    c_mem[c_mem==-1]=1
    print(c_mem)
    print(len(np.unique(c_mem)))
        
    A_m = csr_matrix((np.ones(n, dtype='int'),
                (np.arange(n),c_mem)), shape=(n,len(np.unique(c_mem))))
    #print(A_m[l].shape)
        
    A = A_m
    A = np.sqrt(1/L)*A
    return A


In [55]:
clus_en_matrix(X, 8)  # to which clusters belongs to

[0 0 0 ... 0 0 0]
2


<8043x2 sparse matrix of type '<class 'numpy.float64'>'
	with 8043 stored elements in Compressed Sparse Row format>

In [22]:
pd.set_option('display.max_columns', 6)

In [77]:
for n_file in range(n_files):
    inp_files = [i for i in range(n_files) if i!=n_file] + [n_file]
    inp = []
    for j in range(n_files):
        ind_files = [i for i, x in enumerate(indexes) if x==inp_files[j]]  # all indexes with number 1,2,3,...,46,1
        inp.extend(ind_files)  # concatenate indexes in loop
    new_indexes = indexes[inp]  # новый порядок объектов
    
    # какие объекы в последних контрольных снимках
    tes_test = np.isin(indexes, inp_files[len(inp_files)-n_test_files:len(inp_files)])  # inp_files[46:46]
    n_test_0 = sum(tes_test)  # количество объектов в контрольной выборке = 277
        
    # какие объекы в неточных снимках
    tes_uncertain = np.isin(indexes, inp_files[n_certain_files:n_certain_files+n_uncertain_files])  # 1,2,...,45
    n_uncertain = sum(tes_uncertain)  # количество объектов в неточной выборке = 7766
        
    # какие объекы в точных снимках
    tes_certain = np.isin(indexes, inp_files[:n_certain_files])  # empty
    n_certain = sum(tes_certain)  # количество объектов в точной выборке = 0
        
    X = X0.iloc[inp]
    Y_pos = Y_pos_0.iloc[inp]
    Y1M = Y1M0.iloc[inp]
    
    ind_insult = Y1M==1  # уверенно классиф как больные
    ind_healthy = Y1M==0  # уверенно классиф как здоровые
    ind_certain = np.logical_or(ind_insult,ind_healthy)  # 4958 уверенно классифицированных данных
    
    Y10Tr = np.array([[*ind_insult[:n_certain], *Y_pos[n_certain:n_certain+n_uncertain], *pd.Series(np.zeros((n_test_0,), dtype=int))],
                      [*ind_healthy[:n_certain], *(1-Y_pos[n_certain:n_certain+n_uncertain]), *pd.Series(np.zeros((n_test_0,), dtype=int))]]).T
    
    Y1MC = Y1M[n-n_test_0:len(Y1M)]  # 8043-277 : 8043 (last)
    Y_true_test = 1+(Y1MC[ind_certain[n-n_test_0:len(ind_certain)]]==0)
    
#     Y10Tr2 = Y10Tr
#     ind_uncertain = np.logical_not(ind_certain)
#     Y10Tr2[ind_uncertain][n_certain:n-n_test_0, :] = 0
    
    #print(Y10Tr2)
    
    sigma = 1.25
    bet = 0.001
    mmax = 1000
    G = bet * eye(n, dtype='int') + csr_matrix(([*pd.to_numeric(ind_certain[:n_certain], errors='coerce'),
                 *np.ones(n_uncertain, dtype='int'),
                 *np.zeros(n_test_0, dtype='int')],
                (np.arange(n),np.arange(n))), shape=(n,n))
    G2 = bet * eye(n, dtype='int') + csr_matrix(([*pd.to_numeric(ind_certain[:n-n_test_0], errors='coerce'),
                  *np.zeros(n_test_0, dtype='int')],
                (np.arange(n),np.arange(n))), shape=(n,n))
    
    A = clus_en_matrix(X,1.15)
    m = A.shape[1]  # 1046 in order of 1055
    u = A.sum(axis = 0)  # by columns
    dd = A * u.conj().transpose()  # 8043x1 array
    dd[dd<0] = 0
    D = csr_matrix(([item for sublist in dd.tolist() for item in sublist], 
                    (np.arange(n), np.arange(n))), shape=(n,n), dtype='int')
    D = csr_matrix((1/np.sqrt(D.diagonal()),
                    (np.arange(n), np.arange(n))), shape=(n,n))
    U = D*A
    Gm = csr_matrix((1/G.diagonal(),
                    (np.arange(n), np.arange(n))), shape=(n,n))
    A1 = bet * Gm * U
    A2 = eye(m, dtype='int') - bet*(U.conj().transpose() * Gm)*U

    F = np.empty(shape=[n,K]) 
    for k in range(K):
        A3 = inv(A2) * (U.conj().transpose() * Gm * Y10Tr[:,k])
        F[:,k] = Gm * Y10Tr[:,k] + A1 * A3
        
    #F = F/F.sum(axis = 1).reshape((n,1))  # нормировка
    Ff = F[n-n_test_0:,]
    Ft = Ff[ind_certain[n-n_test_0:],]

    class11 = Ft[Y_true_test==2, 0]  # negative
    class21 = Ft[Y_true_test==1, 0]  # positive
    roc_curve(class11, class21, 1)
    print(n_file)



[  0   1   0 ... 266 266 266]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6714690821414132
Distance: [0.19828615]
Sensitivity: 0.9485294117647058
Specificity: 0.8085106382978723
Accuracy: 0.912568306010929
PPV: 0.9347826086956522
NPV: 0.8444444444444444
FNR: 0.051470588235294115
FPR: 0.19148936170212766
FDR: 0.06521739130434782
FOR: 0.15555555555555556
F1 score: 0.9416058394160584
TP: 129
FP: 9
FN: 7
TN: 38
0
[ 1  0  0 ...  1 22  1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6587454766288853
Distance: [0.31421001]
Sensitivity: 0.9
Specificity: 0.7021276595744681
Accuracy: 0.8651685393258427
PPV: 0.9339622641509434
NPV: 0.6
FNR: 0.1
FPR: 0.2978723404255319
FDR: 0.0660377358490566
FOR: 0.4
F1 score: 0.9166666666666666
TP: 198
FP: 14
FN: 22
TN: 33
1
[ 1  0  0 ...  1  1 22]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5849673721680287
Distance: [0.34675535]
Sensitivity: 0.9044585987261147
Specificity: 0.6666666666666666
Accuracy: 0.8571428571428571
PPV: 0.9161290322580645
NPV: 0.6341463414634146
FNR: 0.09554140127388536
FPR: 0.3333333333333333
FDR: 0.08387096774193549
FOR: 0.36585365853658536
F1 score: 0.9102564102564102
TP: 142
FP: 13
FN: 15
TN: 26
2
[ 1  0  0 ...  1 22  1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5755183921836335
Distance: [0.50483284]
Sensitivity: 0.9303135888501742
Specificity: 0.5
Accuracy: 0.889589905362776
PPV: 0.9468085106382979
NPV: 0.42857142857142855
FNR: 0.06968641114982578
FPR: 0.5
FDR: 0.05319148936170213
FOR: 0.5714285714285714
F1 score: 0.9384885764499121
TP: 267
FP: 15
FN: 20
TN: 15
3
[ 1  0  0 ... 22 22  1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5204987221943265
Distance: [0.34408994]
Sensitivity: 0.8771929824561403
Specificity: 0.6785714285714286
Accuracy: 0.8492462311557789
PPV: 0.9433962264150944
NPV: 0.475
FNR: 0.12280701754385964
FPR: 0.32142857142857145
FDR: 0.05660377358490566
FOR: 0.525
F1 score: 0.9090909090909091
TP: 150
FP: 9
FN: 21
TN: 19
4
[  1   0   0 ... 237  22 344]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5852598277077644
Distance: [0.3239958]
Sensitivity: 0.8888888888888888
Specificity: 0.6956521739130435
Accuracy: 0.8073394495412844
PPV: 0.8
NPV: 0.8205128205128205
FNR: 0.1111111111111111
FPR: 0.30434782608695654
FDR: 0.2
FOR: 0.1794871794871795
F1 score: 0.8421052631578947
TP: 56
FP: 14
FN: 7
TN: 32
5
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6996839545436777
Distance: [0.25581395]
Sensitivity: 1.0
Specificity: 0.7441860465116279
Accuracy: 0.78
PPV: 0.3888888888888889
NPV: 1.0
FNR: 0.0
FPR: 0.2558139534883721
FDR: 0.6111111111111112
FOR: 0.0
F1 score: 0.56
TP: 7
FP: 11
FN: 0
TN: 32
6
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5830048639713776
Distance: [0.47826087]
Sensitivity: 0.5217391304347826
Specificity: 1.0
Accuracy: 0.725
PPV: 1.0
NPV: 0.6071428571428571
FNR: 0.4782608695652174
FPR: 0.0
FDR: 0.0
FOR: 0.39285714285714285
F1 score: 0.6857142857142857
TP: 12
FP: 0
FN: 11
TN: 17
7
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: -0.4053275371107795
Distance: [1.]
Sensitivity: 1.0
Specificity: 0.0
Accuracy: 0.42857142857142855
PPV: 0.42857142857142855
NPV: nan
FNR: 0.0
FPR: 1.0
FDR: 0.5714285714285714
FOR: nan
F1 score: 0.6
TP: 30
FP: 40
FN: 0
TN: 0
8


C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:60: RuntimeWarning: invalid value encountered in long_scalars
  print('FOR:', FN/(FN+TN))


[ 1  0  0 ...  1 22 22]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6245079694706722
Distance: [0.10416667]
Sensitivity: 1.0
Specificity: 0.8958333333333334
Accuracy: 0.9166666666666666
PPV: 0.7058823529411765
NPV: 1.0
FNR: 0.0
FPR: 0.10416666666666667
FDR: 0.29411764705882354
FOR: 0.0
F1 score: 0.8275862068965517
TP: 12
FP: 5
FN: 0
TN: 43
9
[  1   0   0 ...   1   1 504]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.588177907801597
Distance: [0.42228719]
Sensitivity: 0.6666666666666666
Specificity: 0.7407407407407407
Accuracy: 0.7222222222222222
PPV: 0.46153846153846156
NPV: 0.8695652173913043
FNR: 0.3333333333333333
FPR: 0.25925925925925924
FDR: 0.5384615384615384
FOR: 0.13043478260869565
F1 score: 0.5454545454545454
TP: 12
FP: 14
FN: 6
TN: 40
10
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1


 ROC CURVE PARAMETERS:

Threshold: -0.41292419816806253
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 64
FN: 0
TN: 0
11
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1


 ROC CURVE PARAMETERS:

Threshold: -0.41259858155716905
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 63
FN: 0
TN: 0
12
[  1   0   0 ...  22 136   1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5857107877764175
Distance: [0.28526734]
Sensitivity: 0.7466666666666667
Specificity: 0.8688524590163934
Accuracy: 0.8014705882352942
PPV: 0.875
NPV: 0.7361111111111112
FNR: 0.25333333333333335
FPR: 0.13114754098360656
FDR: 0.125
FOR: 0.2638888888888889
F1 score: 0.8057553956834532
TP: 56
FP: 8
FN: 19
TN: 53
13
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.7008709802742881
Distance: [0.41084469]
Sensitivity: 0.6190476190476191
Specificity: 0.8461538461538461
Accuracy: 0.7570093457943925
PPV: 0.7222222222222222
NPV: 0.7746478873239436
FNR: 0.38095238095238093
FPR: 0.15384615384615385
FDR: 0.2777777777777778
FOR: 0.22535211267605634
F1 score: 0.6666666666666666
TP: 26
FP: 10
FN: 16
TN: 55
14
[  1   0   0 ...   1 243   1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6621578539763976
Distance: [0.69403161]
Sensitivity: 0.3181818181818182
Specificity: 0.8703703703703703
Accuracy: 0.7105263157894737
PPV: 0.5
NPV: 0.7580645161290323
FNR: 0.6818181818181818
FPR: 0.12962962962962962
FDR: 0.5
FOR: 0.24193548387096775
F1 score: 0.3888888888888889
TP: 7
FP: 7
FN: 15
TN: 47
15
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5111435873971635
Distance: [0.89134157]
Sensitivity: 0.11428571428571428
Specificity: 0.9
Accuracy: 0.5333333333333333
PPV: 0.5
NPV: 0.5373134328358209
FNR: 0.8857142857142857
FPR: 0.1
FDR: 0.5
FOR: 0.4626865671641791
F1 score: 0.18604651162790697
TP: 4
FP: 4
FN: 31
TN: 36
16
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5811654389320466
Distance: [0.42257205]
Sensitivity: 0.6323529411764706
Specificity: 0.7916666666666666
Accuracy: 0.6739130434782609
PPV: 0.8958333333333334
NPV: 0.4318181818181818
FNR: 0.36764705882352944
FPR: 0.20833333333333334
FDR: 0.10416666666666667
FOR: 0.5681818181818182
F1 score: 0.7413793103448276
TP: 43
FP: 5
FN: 25
TN: 19
17
[ 1  0  0 ...  1  1 22]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5881307353764118
Distance: [0.27834651]
Sensitivity: 0.868421052631579
Specificity: 0.7547169811320755
Accuracy: 0.8021978021978022
PPV: 0.717391304347826
NPV: 0.8888888888888888
FNR: 0.13157894736842105
FPR: 0.24528301886792453
FDR: 0.2826086956521739
FOR: 0.1111111111111111
F1 score: 0.7857142857142857
TP: 33
FP: 13
FN: 5
TN: 40
18
[  1   0   0 ...   1 275  66]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6152220692519005
Distance: [0.38151752]
Sensitivity: 0.8269230769230769
Specificity: 0.66
Accuracy: 0.7450980392156863
PPV: 0.7166666666666667
NPV: 0.7857142857142857
FNR: 0.17307692307692307
FPR: 0.34
FDR: 0.2833333333333333
FOR: 0.21428571428571427
F1 score: 0.7678571428571429
TP: 43
FP: 17
FN: 9
TN: 33
19
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5890137249943088
Distance: [0.32891354]
Sensitivity: 0.9166666666666666
Specificity: 0.6818181818181818
Accuracy: 0.7321428571428571
PPV: 0.44
NPV: 0.967741935483871
FNR: 0.08333333333333333
FPR: 0.3181818181818182
FDR: 0.56
FOR: 0.03225806451612903
F1 score: 0.5945945945945946
TP: 11
FP: 14
FN: 1
TN: 30
20
[  1   0   0 ... 502 280   1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1


 ROC CURVE PARAMETERS:

Threshold: -0.4089875121162814
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 50
FN: 0
TN: 0
21
[ 1  0  0 ...  1 22 22]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.7713705425409579
Distance: [0.68906167]
Sensitivity: 0.45454545454545453
Specificity: 0.5789473684210527
Accuracy: 0.5588235294117647
PPV: 0.1724137931034483
NPV: 0.8461538461538461
FNR: 0.5454545454545454
FPR: 0.42105263157894735
FDR: 0.8275862068965517
FOR: 0.15384615384615385
F1 score: 0.25
TP: 5
FP: 24
FN: 6
TN: 33
22
[  1   0   0 ... 150   1   1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5900970789361275
Distance: [0.54294068]
Sensitivity: 0.6666666666666666
Specificity: 0.5714285714285714
Accuracy: 0.5818181818181818
PPV: 0.16
NPV: 0.9333333333333333
FNR: 0.3333333333333333
FPR: 0.42857142857142855
FDR: 0.84
FOR: 0.06666666666666667
F1 score: 0.25806451612903225
TP: 4
FP: 21
FN: 2
TN: 28
23
[  1   0   0 ...  22   1 164]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.20321782958892198
Distance: [0.88888889]
Sensitivity: 1.0
Specificity: 0.1111111111111111
Accuracy: 0.13043478260869565
PPV: 0.024390243902439025
NPV: 1.0
FNR: 0.0
FPR: 0.8888888888888888
FDR: 0.975609756097561
FOR: 0.0
F1 score: 0.047619047619047616
TP: 1
FP: 40
FN: 0
TN: 5
24
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1


 ROC CURVE PARAMETERS:

Threshold: -0.4080186757694973
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 30
FN: 0
TN: 0
25
[  1   0   0 ... 212   1   1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.20267823659527567
Distance: [0.93169499]
Sensitivity: 0.8333333333333334
Specificity: 0.08333333333333333
Accuracy: 0.23333333333333334
PPV: 0.18518518518518517
NPV: 0.6666666666666666
FNR: 0.16666666666666666
FPR: 0.9166666666666666
FDR: 0.8148148148148148
FOR: 0.3333333333333333
F1 score: 0.30303030303030304
TP: 5
FP: 22
FN: 1
TN: 2
26
[1 0 0 ... 1 1 5]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6737999567115619
Distance: [0.3621348]
Sensitivity: 0.918918918918919
Specificity: 0.6470588235294118
Accuracy: 0.8767123287671232
PPV: 0.9340659340659341
NPV: 0.5945945945945946
FNR: 0.08108108108108109
FPR: 0.35294117647058826
FDR: 0.06593406593406594
FOR: 0.40540540540540543
F1 score: 0.9264305177111717
TP: 170
FP: 12
FN: 15
TN: 22
27
[1 0 0 ... 1 5 5]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6571039874264133
Distance: [0.68032506]
Sensitivity: 0.8643617021276596
Specificity: 0.3333333333333333
Accuracy: 0.8479381443298969
PPV: 0.975975975975976
NPV: 0.07272727272727272
FNR: 0.1356382978723404
FPR: 0.6666666666666666
FDR: 0.024024024024024024
FOR: 0.9272727272727272
F1 score: 0.9167842031029619
TP: 325
FP: 8
FN: 51
TN: 4
28
[  1   0   0 ...   1 502   1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1


 ROC CURVE PARAMETERS:

Threshold: -0.12020657698667056
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 69
FN: 0
TN: 0
29
[  1   0   0 ...   1   1 503]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.20177340890399953
Distance: [0.87013639]
Sensitivity: 0.875
Specificity: 0.1388888888888889
Accuracy: 0.3229166666666667
PPV: 0.25301204819277107
NPV: 0.7692307692307693
FNR: 0.125
FPR: 0.8611111111111112
FDR: 0.7469879518072289
FOR: 0.23076923076923078
F1 score: 0.3925233644859813
TP: 21
FP: 62
FN: 3
TN: 10
30
[ 1  0  0 ... 22 22 22]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.7294026406533796
Distance: [0.34750113]
Sensitivity: 0.9302325581395349
Specificity: 0.6595744680851063
Accuracy: 0.7888888888888889
PPV: 0.7142857142857143
NPV: 0.9117647058823529
FNR: 0.06976744186046512
FPR: 0.3404255319148936
FDR: 0.2857142857142857
FOR: 0.08823529411764706
F1 score: 0.8080808080808081
TP: 40
FP: 16
FN: 3
TN: 31
31
[  1   0   0 ...   1 178   1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6071096760489396
Distance: [0.25893042]
Sensitivity: 0.8048780487804879
Specificity: 0.8297872340425532
Accuracy: 0.8181818181818182
PPV: 0.8048780487804879
NPV: 0.8297872340425532
FNR: 0.1951219512195122
FPR: 0.1702127659574468
FDR: 0.1951219512195122
FOR: 0.1702127659574468
F1 score: 0.8048780487804879
TP: 33
FP: 8
FN: 8
TN: 39
32
[ 1  0  0 ... 22 22 22]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5885172316204063
Distance: [0.43953568]
Sensitivity: 0.9024390243902439
Specificity: 0.5714285714285714
Accuracy: 0.7222222222222222
PPV: 0.6379310344827587
NPV: 0.875
FNR: 0.0975609756097561
FPR: 0.42857142857142855
FDR: 0.3620689655172414
FOR: 0.125
F1 score: 0.7474747474747475
TP: 37
FP: 21
FN: 4
TN: 28
33
[ 1  0  0 ...  1 22  1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.7402604969910849
Distance: [0.39510318]
Sensitivity: 0.6666666666666666
Specificity: 0.7878787878787878
Accuracy: 0.7619047619047619
PPV: 0.46153846153846156
NPV: 0.896551724137931
FNR: 0.3333333333333333
FPR: 0.21212121212121213
FDR: 0.5384615384615384
FOR: 0.10344827586206896
F1 score: 0.5454545454545454
TP: 6
FP: 7
FN: 3
TN: 26
34
[  1   0   0 ...   1 349  22]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5868524980848941
Distance: [0.21212838]
Sensitivity: 0.8837209302325582
Specificity: 0.8225806451612904
Accuracy: 0.8476190476190476
PPV: 0.7755102040816326
NPV: 0.9107142857142857
FNR: 0.11627906976744186
FPR: 0.1774193548387097
FDR: 0.22448979591836735
FOR: 0.08928571428571429
F1 score: 0.8260869565217391
TP: 38
FP: 11
FN: 5
TN: 51
35
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.6443661494569529
Distance: [0.27042428]
Sensitivity: 0.7916666666666666
Specificity: 0.8275862068965517
Accuracy: 0.8113207547169812
PPV: 0.7916666666666666
NPV: 0.8275862068965517
FNR: 0.20833333333333334
FPR: 0.1724137931034483
FDR: 0.20833333333333334
FOR: 0.1724137931034483
F1 score: 0.7916666666666666
TP: 38
FP: 10
FN: 10
TN: 48
36
[  1   0   0 ... 116  91 504]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.645954507943368
Distance: [0.23351648]
Sensitivity: 0.9642857142857143
Specificity: 0.7692307692307693
Accuracy: 0.8375
PPV: 0.6923076923076923
NPV: 0.975609756097561
FNR: 0.03571428571428571
FPR: 0.23076923076923078
FDR: 0.3076923076923077
FOR: 0.024390243902439025
F1 score: 0.8059701492537313
TP: 27
FP: 12
FN: 1
TN: 40
37
[  1   0   0 ...   1 504 504]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.48017752291085936
Distance: [0.92337612]
Sensitivity: 0.08333333333333333
Specificity: 0.8888888888888888
Accuracy: 0.37333333333333335
PPV: 0.5714285714285714
NPV: 0.35294117647058826
FNR: 0.9166666666666666
FPR: 0.1111111111111111
FDR: 0.42857142857142855
FOR: 0.6470588235294118
F1 score: 0.14545454545454545
TP: 4
FP: 3
FN: 44
TN: 24
38
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.5048615462001651
Distance: [0.85076059]
Sensitivity: 0.16326530612244897
Specificity: 0.8461538461538461
Accuracy: 0.24324324324324326
PPV: 0.8888888888888888
NPV: 0.11827956989247312
FNR: 0.8367346938775511
FPR: 0.15384615384615385
FDR: 0.1111111111111111
FOR: 0.8817204301075269
F1 score: 0.27586206896551724
TP: 32
FP: 4
FN: 164
TN: 22
39
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.8008012000616296
Distance: [0.89236277]
Sensitivity: 0.10810810810810811
Specificity: 0.9710144927536232
Accuracy: 0.5244755244755245
PPV: 0.8
NPV: 0.5037593984962406
FNR: 0.8918918918918919
FPR: 0.028985507246376812
FDR: 0.2
FOR: 0.49624060150375937
F1 score: 0.19047619047619047
TP: 8
FP: 2
FN: 66
TN: 67
40
[  1   0   0 ... 495  21   1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.9257884436937955
Distance: [0.92365902]
Sensitivity: 0.07692307692307693
Specificity: 0.9672131147540983
Accuracy: 0.62
PPV: 0.6
NPV: 0.6210526315789474
FNR: 0.9230769230769231
FPR: 0.03278688524590164
FDR: 0.4
FOR: 0.37894736842105264
F1 score: 0.13636363636363635
TP: 3
FP: 2
FN: 36
TN: 59
41
[  1   0   0 ...  22 502 494]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.19463658008649184
Distance: [0.90457477]
Sensitivity: 0.9506172839506173
Specificity: 0.0967741935483871
Accuracy: 0.5804195804195804
PPV: 0.5789473684210527
NPV: 0.6
FNR: 0.04938271604938271
FPR: 0.9032258064516129
FDR: 0.42105263157894735
FOR: 0.4
F1 score: 0.719626168224299
TP: 77
FP: 56
FN: 4
TN: 6
42
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: 0.19679863408062967
Distance: [0.96699243]
Sensitivity: 0.6463414634146342
Specificity: 0.1
Accuracy: 0.5392156862745098
PPV: 0.7464788732394366
NPV: 0.06451612903225806
FNR: 0.35365853658536583
FPR: 0.9
FDR: 0.2535211267605634
FOR: 0.9354838709677419
F1 score: 0.6928104575163399
TP: 53
FP: 18
FN: 29
TN: 2
43
[  1   0   0 ...   1 166  22]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1


 ROC CURVE PARAMETERS:

Threshold: -0.4089731340204516
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 55
FN: 0
TN: 0
44
[1 0 0 ... 1 1 1]
505


C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '



 ROC CURVE PARAMETERS:

Threshold: -0.40897922078956667
Distance: [nan]
Sensitivity: nan
Specificity: 0.0
Accuracy: 0.0
PPV: 0.0
NPV: nan
FNR: nan
FPR: 1.0
FDR: 1.0
FOR: nan
F1 score: 0.0
TP: 0
FP: 41
FN: 0
TN: 0
45


C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:35: RuntimeWarning: invalid value encountered in long_scalars
  curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:56: RuntimeWarning: invalid value encountered in long_scalars
  print('NPV:', TN/(TN+FN))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:57: RuntimeWarning: invalid value encountered in long_scalars
  print('FNR:', FN/(FN+TP))
C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/3470959793.py:60: RuntimeWarning: invalid value encountered in long_scalars
  print('FOR:', FN/(FN+TN))


In [42]:
n_file = 0
inp_files = [i for i in range(n_files) if i!=n_file] + [n_file]
inp = []
for j in range(n_files):
    ind_files = [i for i, x in enumerate(indexes) if x==inp_files[j]]  # all indexes with number 1,2,3,...,46,1
    inp.extend(ind_files)  # concatenate indexes in loop
new_indexes = indexes[inp]  # новый порядок объектов

# какие объекы в последних контрольных снимках
tes_test = np.isin(indexes, inp_files[len(inp_files)-n_test_files:len(inp_files)])  # inp_files[46:46]
n_test_0 = sum(tes_test)  # количество объектов в контрольной выборке = 277

# какие объекы в неточных снимках
tes_uncertain = np.isin(indexes, inp_files[n_certain_files:n_certain_files+n_uncertain_files])  # 1,2,...,45
n_uncertain = sum(tes_uncertain)  # количество объектов в неточной выборке = 7766

# какие объекы в точных снимках
tes_certain = np.isin(indexes, inp_files[:n_certain_files])  # empty
n_certain = sum(tes_certain)  # количество объектов в точной выборке = 0

X = X0.iloc[inp]
Y_pos = Y_pos_0.iloc[inp]
Y1M = Y1M0.iloc[inp]

ind_insult = Y1M==1  # уверенно классиф как больные
ind_healthy = Y1M==0  # уверенно классиф как здоровые
ind_certain = np.logical_or(ind_insult,ind_healthy)  # 4958 уверенно классифицированных данных

Y10Tr = np.array([[*ind_insult[:n_certain], *Y_pos[n_certain:n_certain+n_uncertain], *pd.Series(np.zeros((n_test_0,), dtype=int))],
                  [*ind_healthy[:n_certain], *(1-Y_pos[n_certain:n_certain+n_uncertain]), *pd.Series(np.zeros((n_test_0,), dtype=int))]]).T

Y1MC = Y1M[n-n_test_0:len(Y1M)]  # 8043-277 : 8043 (last)
Y_true_test = 1+(Y1MC[ind_certain[n-n_test_0:len(ind_certain)]]==0)

#     Y10Tr2 = Y10Tr
#     ind_uncertain = np.logical_not(ind_certain)
#     Y10Tr2[ind_uncertain][n_certain:n-n_test_0, :] = 0

#print(Y10Tr2)

sigma = 1.25
bet = 0.001
mmax = 1000
G = bet * eye(n, dtype='int') + csr_matrix(([*pd.to_numeric(ind_certain[:n_certain], errors='coerce'),
             *np.ones(n_uncertain, dtype='int'),
             *np.zeros(n_test_0, dtype='int')],
            (np.arange(n),np.arange(n))), shape=(n,n))
G2 = bet * eye(n, dtype='int') + csr_matrix(([*pd.to_numeric(ind_certain[:n-n_test_0], errors='coerce'),
              *np.zeros(n_test_0, dtype='int')],
            (np.arange(n),np.arange(n))), shape=(n,n))

A = clus_en_matrix(X,10)
m = A.shape[1]  # 1046 in order of 1055
u = A.sum(axis = 0)  # by columns
dd = A * u.conj().transpose()  # 8043x1 array
dd[dd<0] = 0
D = csr_matrix(([item for sublist in dd.tolist() for item in sublist], 
                (np.arange(n), np.arange(n))), shape=(n,n), dtype='int')
D = csr_matrix((1/np.sqrt(D.diagonal()),
                (np.arange(n), np.arange(n))), shape=(n,n))
U = D*A
Gm = csr_matrix((1/G.diagonal(),
                (np.arange(n), np.arange(n))), shape=(n,n))
A1 = bet * Gm * U
A2 = eye(m, dtype='int') - bet*(U.conj().transpose() * Gm)*U

F = np.empty(shape=[n,K]) 
for k in range(K):
    A3 = inv(A2) * (U.conj().transpose() * Gm * Y10Tr[:,k])
    #print('A3 -> ', A3)
    F[:,k] = Gm * Y10Tr[:,k] + A1 * A3
    #print('F[:,k] -> ', F[:,k])

#F = F/F.sum(axis = 1).reshape((n,1))  # нормировка
Ff = F[n-n_test_0:,]
Ft = Ff[ind_certain[n-n_test_0:],]

class11 = Ft[Y_true_test==2, 0]  # negative
class21 = Ft[Y_true_test==1, 0]  # positive

[0 0 0 ... 0 0 0]
2


C:\Users\KUNASY~1.DES\AppData\Local\Temp/ipykernel_11940/1916063652.py:59: RuntimeWarning: divide by zero encountered in true_divide
  D = csr_matrix((1/np.sqrt(D.diagonal()),
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\Kunasyl.DESKTOP-N9JUTUQ\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '


In [66]:
F

array([[0.41144129, 0.58855871],
       [0.39443614, 0.60556386],
       [0.44918354, 0.55081646],
       ...,
       [0.92862961, 0.07137039],
       [0.92862961, 0.07137039],
       [0.92862961, 0.07137039]])

In [62]:
A2.toarray()

array([[ 0.999001  ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.97582194,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.99875125, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.66666667,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.66666667,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.66666667]])

In [63]:
A.toarray()

array([[0.91287093, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.91287093, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.91287093, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [29]:
dd

matrix([[150.7],
        [142.5],
        [159.6],
        ...,
        [141.1],
        [122.2],
        [128.3]])

In [31]:
U.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.02581989],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.02653724],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [32]:
Y10Tr

array([[0.41111, 0.58889],
       [0.39444, 0.60556],
       [0.44889, 0.55111],
       ...,
       [0.     , 0.     ],
       [0.     , 0.     ],
       [0.     , 0.     ]])

In [63]:
len(Y10Tr2[ind_uncertain][n_certain:n-n_test_0, :])  #should be 3001

3085

In [65]:
len(Y10Tr2)

8043

In [64]:
Y10Tr2[ind_uncertain[n_certain:n-n_test_0],:]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 8043 but corresponding boolean dimension is 7766

In [66]:
ind_uncertain[n_certain:n-n_test_0]

230      True
231      True
232      True
233      True
234      True
        ...  
2103    False
2104    False
2105    False
2106    False
2107    False
Length: 7766, dtype: bool

In [68]:
Y10Tr

array([[0.41111, 0.58889],
       [0.39444, 0.60556],
       [0.44889, 0.55111],
       ...,
       [0.     , 0.     ],
       [0.     , 0.     ],
       [0.     , 0.     ]])

In [59]:
def roc_curve(class_1, class_2, disp_data):  # negative, positive
#     rng(1337,'twister')
#     s = rng
#     class_1 = rand(1,3);
#     rng(s)
#     class_2 = 0.5*rand(1,5);
#     sispt = 1;
#     dispp = 1;

#     np.random.seed(1337)
#     class_1 = np.random.rand(1,3)
#     np.random.seed(1337)
#     class_2 = 0.5*np.random.rand(1,3)

    # Calculating the threshold values between the data points
    s_data = np.sort(np.unique(np.concatenate([class_1, class_2], axis=0)))
    s_data = s_data[s_data!=np.array(None)]
    d_data = np.diff(s_data)
    if np.all(d_data==0):
        print('Both class are the same!')
    d_data = np.append(d_data, d_data[-1])
    thres = np.empty(len(s_data)+1)
    thres[0] = s_data[0] - d_data[0]
    thres[1:len(thres)] = s_data + d_data/2

    # Calculating the sensibility and specificity of each threshold
    curve = np.zeros((len(thres),2))
    distance = np.zeros((len(thres),1))
    for id_t in range(len(thres)):
        TP = np.sum(class_2 >= thres[id_t])
        FP = np.sum(class_1 >= thres[id_t])
        FN = np.sum(class_2 < thres[id_t])
        TN = np.sum(class_1 < thres[id_t])

        curve[id_t, 0] = TP/(TP+FN)  # sensitivity - TPR
        curve[id_t, 1] = TN/(TN+FP)  # specificity - FPR

        distance[id_t] = np.sqrt((1-curve[id_t, 0])**2 + (curve[id_t,1]-1)**2)

    # Optimum threshold and parameters
    #opt = np.min(distance)  # 1
    opt = np.argmin(distance)
    TP = np.sum(class_2 >= thres[opt])
    FP = np.sum(class_1 >= thres[opt])
    FN = np.sum(class_2 < thres[opt])
    TN = np.sum(class_1 < thres[opt])

    if disp_data==1:
        print('\n ROC CURVE PARAMETERS:\n')
        print('Threshold:', thres[opt])
        print('Distance:', distance[opt])
        print('Sensitivity:', curve[opt,0])
        print('Specificity:', curve[opt,1])
        print('Accuracy:', (TP+TN)/(TP+TN+FP+FN))
        print('PPV:', TP/(TP+FP))
        print('NPV:', TN/(TN+FN))
        print('FNR:', FN/(FN+TP))
        print('FPR:', FP/(FP+TN))
        print('FDR:', FP/(FP+TP))
        print('FOR:', FN/(FN+TN))
        print('F1 score:', 2*TP/(2*TP+FP+FN))
        print('TP:', TP)
        print('FP:', FP)
        print('FN:', FN)
        print('TN:', TN)